
<?php if (!$block->customerIsAlreadyLoggedIn() && $block->getRegistration()->isAllowed()): ?>
    <style>
        .customer-popup-register {
            display: none;
        }

        header.modal-header .modal-title{
  border: none;
    font-size: 28px;
    font-family: arial black;
}


.legend{
    border:none;
}


.control #firstname{
    margin-top:3px;
    height:42px;
    border-radius: 6px;
    width: 49%;
}

.control #lastname{
    height: 42px;
    border-radius: 6px;
    width: 49%;
    float:right;
    position:relative;
    top: -62px;
}


#popup-email_address{
    height: 42px;
    border-radius: 6px;
    width: 49%;
    position: relative;
    top: -40px;
    left:267px;
}

#password{
    width: 100%;
    height: 42px;
    border-radius: 6px;
    margin-bottom: 3%;
}

#password-confirmation{
    width: 100%;
    height: 42px;
    border-radius: 6px;
    margin-bottom: 3%;  
}

#dob._has-datepicker{
    width: 49%;
    height: 42px;
    border-radius: 6px;
}

#div-container{
    position:relative;
    border: px solid black;
    top:-65px;
}

#signup-newsletter{
    margin-bottom: 3%;
    font-family: arial;
}

#or-selection{
    margin: 3% 0;
    text-align: center;
    width: 100%;
    font-family: arial black;
    font-size: 14px;
}

.modals-overlay{
    z-index: 899!important;
}

.action.submit.primary{
    width: 100%;
    margin-top:2%;
    height: 42px;
    
}

.action.submit.primary#btn-create-account{
    background: #02B14C;
}

.action.submit.primary#btn-fb-signup{
    background: #4769B0;
}

.action.submit.primary#btn-gmail-signup{
    background: #FC5B61;
}


.action.submit.primary#gmail-logo{
    width: 20px;
    height: 20px;
    position: relative;
    right: 15%;
    top: 2px;
    
}

#create-fb-logo{
    width: 23px;
    height: 20px;
    position: relative;
    right: 4%;
    top: 2px;
    
}

#create-gmail-logo{
    width: 22px;
    height: 20px;
    position: relative;
    right: 6%;
    top: 2px;
    
}

#accounts-selection{
    text-align: center;
    width: 100%;
    margin-top: 7%;
    font-family: arial black;
    color: #02B14C;
}

.form-create-account{
    height: 400px;
}

#firstname-error,#lastname-error,
#password-error,#password-confirmation-error{
    display: none !important;
}

button.ui-datepicker-trigger.v-middle{
    display: none;
}
    </style>
    <div id="customer-popup-register" class="customer-popup-register">
        <form class="form-create-account" action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>" method="post" id="customer-popup-form-register" enctype="multipart/form-data" autocomplete="off" data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey'); ?>
            <input type="hidden" name="redirect_url" value="<?php echo $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>" />
            <div class="messages"></div>
             <fieldset class="fieldset create info">
                <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                 <!-- Date Kuno -->   
                 
                <div class="field required">
                     <?php 
                         echo $block->getLayout()
                        ->createBlock('Magento\Customer\Block\Widget\Dob')
                        ->toHtml()
                     ?>
                   <!-- <label for="popup-email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label> -->
                   
                       <input placeholder="EMAIL" type="email" name="email" autocomplete="email" id="popup-email_address" value="" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
                   
               </div>
            </fieldset>
            <div id="div-container"> 
                
                <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
                    <!-- <label for="password" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label> -->
                    <div class="control">
                        <input placeholder="PASSWORD" type="password" name="password" id="password"
                               title="<?php /* @escapeNotVerified */ echo __('Password') ?>"
                               class="input-text"
                               data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                               data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                               data-validate="{required:true, 'validate-customer-password':true}"
                               autocomplete="off">
                        
                    </div>
                </div>
                <div class="field confirmation required">
                    <!-- <label for="password-confirmation" class="label"><span><?php /* @escapeNotVerified */ echo __('Confirm Password') ?></span></label> -->
                    <div class="control">
                        <input placeholder="CONFIRM PASSWORD" type="password" name="password_confirmation" title="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                    </div>
                </div>
                <?php if ($block->isNewsletterEnabled()): ?>
                    <div id="signup-newsletter" class="field choice newsletter">
                        <input type="checkbox" name="is_subscribed" title="<?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?>" value="1" id="popup-is_subscribed" class="checkbox">
                        <label  for="is_subscribed" class=""><span><?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?></span></label>
                    </div>
                <?php endif ?>
          
            <div class="actions-toolbar">
                <div class="primary">
                    <button id="btn-create-account" type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __("CREATE YOUR ACCOUNT")?>"><span><?php /* @escapeNotVerified */ echo __("CREATE YOUR ACCOUNT") ?></span></button>
                </div>
                <div id="or-selection" class="or-another-selection"><?php echo __('OR'); ?></div>
                <div class="primary">
                    <button id="btn-fb-signup" type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __("SIGN UP WITH FACEBOOK")?>"><span><img id="create-fb-logo" src="<?php echo 'http://127.0.0.1/zagana/pub/media//.thumbsinserted/fb.png?rand=1580369426';?>"><?php /* @escapeNotVerified */ echo __('SIGN UP WITH FACEBOOK') ?></span></button>
                </div><div class="primary">
                    <button id="btn-gmail-signup" type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __("SIGN UP WITH GOOGLE")?>"><span><img id="create-gmail-logo" src="<?php echo 'http://127.0.0.1/zagana/pub/media//.thumbsinserted/google.png?rand=1580369426';?>"><?php /* @escapeNotVerified */ echo __('SIGN UP WITH GOOGLE') ?></span></button>
                </div>
                <div id="accounts-selection" class="or-another-selection"><?php echo __('Already have an Account?'); ?></div>
            </div>
            </div>
        </form>
        <script type="text/x-magento-init">
            {
                "#customer-popup-register": {
                    "ZaganaPH_CustomerAccount/js/action/customer-authentication-popup": {
                        "popupTitle": "<?php /* @escapeNotVerified */ echo __('Create an Account'); ?>",
                        "innerWidth": "600"
                    }
                }
            }
        </script>
    </div>
<?php endif; ?>